version: 1
env:
  - GO111MODULE=on
  # https://stackoverflow.com/a/62821358/19407
  - CGO_ENABLED=0

flags:
  - -trimpath
  # - -mod=readonly

#TODO:
#mod_timestamp: '{{ .CommitTimestamp }}'
goos: linux
goarch: amd64

main: ./cmd/tuf/main.go

binary: tuf-{{ .Os }}-{{ .Arch }}

ldflags:
  - "-s -w"
  - "-extldflags=-zrelro"
  - "-extldflags=-znow"
