version: 1
env:
  - GO111MODULE=on
  - CGO_ENABLED=0

flags:
  - -trimpath

goos: linux
goarch: amd64

main: ./cmd/tuf-client/main.go

binary: tuf-client-{{ .Os }}-{{ .Arch }}

ldflags:
  - "-s -w"
  - "-extldflags=-zrelro"
  - "-extldflags=-znow"